AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - '.circleci/**/*'
    - 'tmp/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'app/assets/bower_components/**/*'

Metrics/LineLength:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Style/Lambda:
  EnforcedStyle: literal

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
