development:
  secret_key_base: 054883204f834e948acf9b87081b0f2188d73594fbb82c97b76ace5a4529ac56e3f036751d44ec13cb449061b4f4b84b34a70e340441c0d4fee6c8668ad327da

production:
  secret_key_base: ENV['SECRET_KEY_BASE']
  secret_access_token: ENV['SECRET_ACCESS_TOKEN']
  secret_access_token_secret: ENV['SECRET_ACCESS_TOKEN_SECRET']
  secret_consumer_key: ENV['SECRET_CONSUMER_KEY']
  secret_consumer_secret: ENV['SECRET_CONSUMER_SECRET']
